config/routes.rb
 Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :products do
    resources :comments

  end

  
  
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'static_pages/index'

  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

   root 'static_pages#landing_page'

  
   resources :orders, only: [:index, :show, :create, :destroy]
  
   

end

app/models/product.rb
class Product < ActiveRecord::Base
	has_many :orders
	has_many :comment

	validates :name, presence: true

	def average_rating
 		comment.average(:rating).to_f
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  protect_from_forgery 
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  
  def index
    if params[:q]
      search_term = params[:q]
      @products = Product.where("name Like ?", "%#{search_term}%")
      # return filtered result
    else
      @products = Product.limit(3)
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
   @comment = @product.comment.order("created_at DESC")
   @comment = @product.comment.paginate(page: params[:page], per_page: 3)
  end

  # GET /products/new
  def new
    @product = Product.new
      end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to "/" }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_product
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<div class="product-reviews">
    <% @comment.each do |comment| %>
        <div class="row">
            <hr>
            <p>
      			<%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small> 
                <% if signed_in? && current_user.admin? %>
                    <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(@product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
      		</p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>

    <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
  <%= f.label :color %><br>
  <%= f.text_field :color %>
  </div>
  <div class="field">
  <%= f.label :price %><br>
  <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
   
<% if signed_in? %>
<div class="container">
        <div class="row" style="margin-top:40px;">
          <div class="col-md-6" style="margin-left:200px;">
            <div class="well well-sm">
              <div class="text-center">
                  <a class="btn btn-success btn-green" id="open-review-box">Leave a Review</a>
              </div>
                  <div class="row " id="post-review-box" style="display:none;">
                  <%= form_for([@product, @product.comment.build], remote: true) do |f| %>
                    <p>
                      <%= f.label :body, "Comments" %><br>
                      <%= f.text_area :body, class: "form-control animated", style: "width: 80%;" "margin-left: 55px;", placeholder: "Enter your review here...", rows: "5" %>
                    </p>
                    <p>
                        <div class="rating"></div>
                    </p> 
                    <p>
                      <%= f.submit "Submit" %>
                    </p>
                  <% end %>
                  </div>
            </div>
        </div>
    </div>
</div>
<% end %>

app/views/products/_product.html.erb
<div class="col-md-4 col-sm-4 hero-feature">

    <div class="thumbnail">
        <% cache product do %>
        <%= image_tag(product.image_url, class: "image-responsive", style: "width: 160px;" "height: 160px;") %>
            <div class="caption">
                <h3><%= product.name %></h3>
                <p><%= product.description %></p>
                <p><%= product.color %></p>
                <h4><strong>$<%= product.price %></strong></h4>
                <p>
                    <a href="#" class="btn btn-primary">Buy Now!</a> <a href="#" class="btn btn-default">More Info</a>
                </p>
                <td><%= link_to 'Show', product %></td>
                <td><%= link_to 'Edit', edit_product_path(product) %></td>
                <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </div>
        <% end %>
    </div>
</div>

app/views/products/_stripe_checkout_button.html.erb
 <script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-image="/square-image.png"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-amount="<%= @product.price*100 %>">
</script>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render partial: 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>


<br>
<div class="container">
  <div class="row">
    <% @products.each do |product| %>
      <%= render product %>
    <% end %>    
  </div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render partial: 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container-fluid col-md-8 col-md-offset-2 panel panel-default" style="border: 2px solid #aba2ab;, border-radius: 10px 10px 10px 10px;, box-shadow: 7px 9px 21px 0px #b1bfc2;">
  <div class="content-wrapper "> 
    
    <div class="item-container">  
      
          <div class="product col-md-8 col-md-offset-2  panel-heading">
                    
            <center>
              <% cache @product do %>
              <%= image_tag(@product.image_url, class: "img-responsive img-zoom", style: "width: 300px;" "height: 300px;", data_zoom_image: "@product.image_url") %>
            </center>
          </div>
          
        </div>
          
        <div class="col-md-8 col-md-offset-2">
          <div class="product-title text-left">
            <h4>
              <strong>Name:</strong>
              <%= @product.name %>
            </h4>
          </div>
          <div class="text-left product-desc">
            <h5>
              <%= @product.description %>
            </h5>
          </div>
          <div class="product-rating"><i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star gold"></i> <i class="fa fa-star-o"></i> </div>
          <hr>
          <div class="product-price text-left">
            <h4>    
              <strong>Price: </strong><%= @product.price %>
            </h4>
          </div>
          <div class="product-color text-left">
            <h4>    
              <strong>Color: </strong><%= @product.color %></div>
              <% end %>
            </h4>
          <hr>
          <p>Average Rating: <div class="rated" data-score="<%= @product.average_rating %>"></div> </p>
          <br>
          <%= form_tag("/payments/create", remote: true) do %>
            <%= render partial: "products/stripe_checkout_button" %>
            
            <%= hidden_field_tag(:product_id, @product.id) %>
            <input type="hidden" value="<%= form_authenticity_token() %>"name="authenticity_token"/>
          <% end %>
          
          <br>
          <div class="btn-group wishlist">
            <button type="button" class="btn btn-danger">
              Add to wishlist 
            </button>
          </div>
          <br>
          <br>
          <%= link_to 'Edit', edit_product_path(@product) %> |
          <%= link_to 'Back', products_path %>
        </div>
        </div>

          
        <br>    
        <br>
      <%= render partial: 'new_comment' %>

      <br>    
      <br>

      <%= render partial: "comments" %>

      <%= will_paginate @comment %>

    <!-- 
    <div class="col-md-8 col-md-offset-2 container-fluid">   
      <div class="product-info">
          <ul id="myTab" class="nav nav-tabs nav_tabs">
            
            <li class="active"><a href="#service-one" data-toggle="tab">DETAILS</a></li>
            <li><a href="#service-two" data-toggle="tab">PRODUCT INFO</a></li>
            <li><a href="#service-three" data-toggle="tab">REVIEWS</a></li>
            
          </ul>
        <div id="myTabContent" class="tab-content">
            <div class="tab-pane fade in active" id="service-one">
             
              <h5 class="container product-info col-md-8 col-md-offset-2">
                <%= @product.description %>
              </h5>
              <br>
              <br>        
            </div>
        </div>

      </div>
    </div>
    

    
  </div>
</div>
-->